https://chromium.googlesource.com/chromium/src/out/
https://ci.chromium.org/ui/p/infra/builders/codesearch/codesearch-gen-chromium-linux/13155/overview
https://sourcegraph.com/search
https://chromium.googlesource.com/chromium/tools/build/
https://chromium.googlesource.com/chromium/tools/build/+/refs/heads/main/recipes/recipe_modules/codesearch/resources/add_kythe_metadata.py
https://groups.google.com/g/kythe/c/xKXE3S1JIRI
https://pkg.go.dev/chromium.googlesource.com/infra/infra.git/go/src/infra/cmd/package_index#section-readme
https://pkg.go.dev/chromium.googlesource.com/infra/infra.git/go/src/infra/cmd/package_index#section-sourcefiles
https://chromium.googlesource.com/infra/infra/+/refs/heads/main/build/packages
https://chrome-infra-packages.appspot.com/p/infra/tools/package_index/linux-amd64/+/n7uPKoIlk_65MaWh11WTaC4gPwtpC9pVF2h_tKfEVQoC
